### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by maxduke** [cmj2002/tantivy-recover#1]
The tool works great for recovering the 0.8.1 index. But it seems to take up a lot of memory. (around 4GB during running)

**Comment by cmj2002** [comment]
Yes, I didn't write the program with memory usage in mind because I only need to run the program once, and 4GB isn't very large for a modern computer. What's more, indexing the CSV file recovered usually uses much more memory, so it is probably pointless to optimize it.

If anyone is running out of memory, he/she can run it in an 8GB instance of GitHub Codespaces.

I might only consider optimizing it if there's a need to recover larger index files in the future. Of course, pull requests are always welcome.
